### ISSUE TITLE
Better selectors

### ISSUE THREAD

**Issue by theKashey** [aweary/react-copy-write#10]
Everything is awesome, except selectors. They are just ordinal selectors, and does not working as usual.

But, as long you are using immer to create a state, you can use the same Proxy-backed magic to select something from a state.

I am talking about memoize-state(https://github.com/theKashey/memoize-state), or react-memoize(https://github.com/theKashey/react-memoize) as example of memoize-state usage.

The first one was created to replace reselect, the second one - to provide memoization, selectors for context or memoized composition to react level. 
You can double check react-memoize sources - it is literally one line. You can do the same.

Then
```js
const UserPosts = ({ userId }) => (
  <State.Consumer
    selector={state => state.posts.filter(post => post.id === userId)}
  >
    {userPosts => userPosts.map(post => <Post {...post} />)}
  </State.Consumer>
);
```
__will work__ out of the box. You need just to memoize selector before use.
```js
state = {
   selector: memoizeState(this.props.selector)
 };
```
And then use memoized selector to actually caclucate things you need.
The solution is IE11 and ReactNative compatible, and quite fast.
More about - https://itnext.io/how-i-wrote-the-worlds-fastest-react-memoization-library-535f89fc4a17

Ready to answer any questions. Lets make this word a bit better.
PS: Not "just opening" PR without a green light.

**Comment by aweary** [comment]
Thanks for the feedback @theKashey! I see the value in having memoized selectors, I just don't want to pay the cost of including a memoization utility by default. In most cases, deriving state in render is good enough.

You can definitely use memoization with the current API though!

```jsx
const getUserPosts = memoize(state => state.posts.filter(post => post.id === state.user.id))

<Consumer selector={getUserPosts}>
  {/* ... */}
</Consumer>
```

**Comment by theKashey** [comment]
Anyway - now you are aware of a possible solution for the "selection problem".

**Comment by aweary** [comment]
I appreciate it! I'm definitely open to adding a note to the documentation mentioning that you can use your own memoization library.
