### ISSUE TITLE
share state instance in multiple components

### ISSUE THREAD

**Issue by vesparny** [aweary/react-copy-write#11]
Hi,
what is the recommended way to create the state and re-use it across components in different files?
Imagine in your app.js you create the state 
```js
const State = createState({
  user: null,
  loggedIn: false
});
```
How do I use `State` and `Providers` in connected components?

I worked on a lib called [statty](https://github.com/vesparny/statty) and one of the most annoying thing is to create a wrapper component when you need the `update` in lifecycle hooks

```js
  <State
    select={selector}
    render={({ count }, update) => (
      <ComponentsThatNeedsToAccessUpdateInLifecycle update={update} />
    )}
  />
```

`createMutator` seems meant to solve this pain, and I wonder what is the suggested way to use it in multiple components :)

Thanks

**Comment by aweary** [comment]
If you need to update state in a lifecycle, using `createMutator` is definitely the recommended way to do it!
